### ISSUE TITLE
remove WARNING: Plugin ServerlessPlugin uses deprecated hook before:deploy:initialize

### ISSUE THREAD

**Issue by WirthAware** [8select/serverless-plugin-api-docs#6]
* remove deprecated hook
* use `package:initialize` hook instead?

**Comment by headwire** [comment]
Warnings will gone with an SLS update. Don't see a point to mute them.
Ref. https://github.com/serverless-heaven/serverless-webpack/issues/126

**Comment by HyperBrain** [comment]
This warning is only a hint for plugin authors to change the hooks to the new separated package and deploy lifecycles. The new hooks should be available since SLS 1.12. I will update them in `serverless-webpack` for the next version (`3.1.0`) and restrict Serverless to 1.12+.
